version: '1'
services:
  customer-management-db:
    image: postgres:16
    container_name: emergency-care-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - emergency_care_data:/var/lib/postgresql/data

volumes:
  emergency_care_data:
