CREATE TABLE health_unit (
  id         SERIAL NOT NULL,
  name       varchar(60) NOT NULL,
  type       varchar(20) NOT NULL,
  capacity   int4 NOT NULL,
  phone      varchar(15),
  street     varchar(60) NOT NULL,
  number     varchar(10) NOT NULL,
  complement varchar(30),
  zipcode    varchar(8) NOT NULL,
  city       varchar(30) NOT NULL,
  state      varchar(2) NOT NULL,
  latitude   numeric(9, 6),
  longitude  numeric(9, 6),
  PRIMARY KEY (id));
