spring:
  application:
    name: health-unit-management
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/health_unit_management
    username: postgres
    password: admin

springdoc:
  swagger-ui:
    operationsSorter: method

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: "${spring.application.name}:${spring.application.instance_id:${random.value}}"

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
info:
  app:
    name: Health Unit Management
    version: 1.0.0
    description: SUSQFree - Health Unit Management
